"""Upp

Revision ID: 471db3077112
Revises: 625cab97bf53
Create Date: 2022-07-24 15:09:55.212702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471db3077112'
down_revision = '625cab97bf53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unrelational', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unrelational')
    # with op.batch_alter_table('unrelational', schema=None) as batch_op:
    #     batch_op.drop_column('name')

    # ### end Alembic commands ###
