"""empty message

Revision ID: 5f371739c99d
Revises: 
Create Date: 2022-07-20 19:06:28.203130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f371739c99d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'deposit', type_='foreignkey')
    op.create_foreign_key(None, 'deposit', 'user', ['user_id'], ['id'])
    op.drop_column('deposit', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('user', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'deposit', type_='foreignkey')
    op.create_foreign_key(None, 'deposit', 'user', ['user'], ['id'])
    op.drop_column('deposit', 'user_id')
    # ### end Alembic commands ###
