"""empty message

Revision ID: 748941e976b8
Revises: 5f371739c99d
Create Date: 2022-07-20 19:28:24.629844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748941e976b8'
down_revision = '5f371739c99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'deposit', type_='foreignkey')
    op.create_foreign_key(None, 'deposit', 'user', ['user_id'], ['id'])
    op.drop_column('deposit', 'user')
    op.add_column('transfer', sa.Column('receiverName', sa.String(length=240), nullable=False))
    op.add_column('transfer', sa.Column('receiverNameAccountNumber', sa.String(length=120), nullable=False))
    op.add_column('transfer', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.create_foreign_key(None, 'transfer', 'user', ['user_id'], ['id'])
    op.drop_column('transfer', 'receiver')
    op.drop_column('transfer', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('user', sa.INTEGER(), nullable=True))
    op.add_column('transfer', sa.Column('receiver', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.create_foreign_key(None, 'transfer', 'user', ['user'], ['id'])
    op.drop_column('transfer', 'user_id')
    op.drop_column('transfer', 'receiverNameAccountNumber')
    op.drop_column('transfer', 'receiverName')
    op.add_column('deposit', sa.Column('user', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'deposit', type_='foreignkey')
    op.create_foreign_key(None, 'deposit', 'user', ['user'], ['id'])
    op.drop_column('deposit', 'user_id')
    # ### end Alembic commands ###
