"""render as batch

Revision ID: 76081aff6fb4
Revises: c355d5973b0d
Create Date: 2022-07-20 19:39:53.402512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76081aff6fb4'
down_revision = 'c355d5973b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_deposit'], ['id'])
        batch_op.drop_column('user')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiverName', sa.String(length=240), nullable=False))
        batch_op.add_column(sa.Column('receiverNameAccountNumber', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('user_transfer', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_transfer'], ['id'])
        batch_op.drop_column('user')
        batch_op.drop_column('receiver')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('user', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user'], ['id'])
        batch_op.drop_column('user_transfer')
        batch_op.drop_column('receiverNameAccountNumber')
        batch_op.drop_column('receiverName')

    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user'], ['id'])

    # ### end Alembic commands ###
