"""TokenBlocklist

Revision ID: cca806f03af9
Revises: 7f2f276c5b64
Create Date: 2022-07-26 14:12:48.317194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cca806f03af9'
down_revision = '7f2f276c5b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_block_list', schema=None) as batch_op:
        batch_op.drop_index('ix_token_block_list_jti')

    op.drop_table('token_block_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_block_list',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('token_block_list', schema=None) as batch_op:
        batch_op.create_index('ix_token_block_list_jti', ['jti'], unique=False)

    # ### end Alembic commands ###
