"""empty message

Revision ID: fbc152e9d334
Revises: 091e1f5dfee0
Create Date: 2022-07-19 16:33:41.199432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc152e9d334'
down_revision = '091e1f5dfee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    op.alter_column('user', 'accountNumber',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'accountBalance',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'accountBalance',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('user', 'accountNumber',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=120), nullable=False),
    sa.Column('lastName', sa.VARCHAR(length=120), nullable=False),
    sa.Column('phoneNumber', sa.VARCHAR(length=120), nullable=False),
    sa.Column('role', sa.VARCHAR(length=120), nullable=False),
    sa.Column('accountNumber', sa.VARCHAR(length=120), nullable=True),
    sa.Column('accountBalance', sa.FLOAT(), nullable=True),
    sa.Column('accountType', sa.VARCHAR(length=120), nullable=False),
    sa.Column('accountStatus', sa.VARCHAR(length=120), nullable=False),
    sa.Column('dateOfBirth', sa.DATETIME(), nullable=False),
    sa.Column('dateCreated', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accountNumber'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phoneNumber')
    )
    # ### end Alembic commands ###
