---
openapi: 3.0.0
info:
  version: 1.0.0
  title: Banking-App
  description: My banking application.
servers:
  - url: http://127.0.0.1:5000
  - url: http://localhost:8080
tags:
  - name: User
    description: Handles everything concerning users.
  - name: Default
    description: The default tag.
  - name: Deposit
    description: Handles the aspect about deposit.
  - name: Transfer
    description: Handles the aspect about transfer.
paths:
  "/api/deposits":
    get:
      tags:
        - Deposit
      summary: Get all deposits
      description: A route to list all deposits
      responses:
        "200":
          description: OK!
          content:
            application/json:
              schema:
                properties:
                  role:
                    type: string
                    example: Customer
        "400":
          description: You are not authorized to do that!
        "404":
          description: Not Found.
        "500":
          description: We are having server issues, don't mind us, lol x.
    post:
      tags:
        - Deposit
      summary: Make a deposit
      description: Make a deposit
      requestBody:
        description: Input the sender, receiver and amount to be deposited
        content:
          application/json:
            schema:
              required:
                - account number
                - sender
                - amount
              properties:
                account number:
                  type: string
                  example: 100000000
                sender:
                  type: string
                  example: James Confidence
                amount:
                  type: number
                  format: float
                  example: 50000
      responses:
        "200":
          description: OK!
          content:
            application/json:
              schema:
                properties:
                  msg:
                    type: string
                    example:
                      50000 deposited successfully to Confidence James with
                      account number of 100000000
        "400":
          description: You are not authorized to do this!
        "404":
          description: Not Found.
        "500":
          description: We are having server issues, don't mind us, lol x.
  "/api/deposits/history":
    get:
      tags:
        - Deposit
      summary: History of deposits.
      description: Get the history of deposits into a user's account.
      responses:
        "200":
          description: OK!
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Date Created:
                      type: string
                      format: date
                      example: 06-12-1970
                    amount:
                      type: number
                      format: float
                      example: 50000
                    sender:
                      type: string
                      example: Confidence James
        "400":
          description: You are not authorized to do that.
        "404":
          description: Not Found.
        "500":
          description: We are having server issues, don't mind us, lol x.
  "/api/deposits/history/{deposit_id}":
    get:
      tags:
        - Deposit
      parameters:
        - in: path
          name: deposit_id
          required: true
          description: Deposit ID
          schema:
            type: integer
            format: int32
      summary: History of deposits.
      description: Get a particular deposit into a user's account.
      responses:
        "200":
          description: OK!
          content:
            application/json:
              schema:
                properties:
                  Date Created:
                    type: string
                    format: date
                    example: 06-12-1970
                  amount:
                    type: number
                    format: float
                    example: 50000
                  sender:
                    type: string
                    example: Confidence James
        "400":
          description: You are not authorized to do that.
        "404":
          description: Not Found.
        "500":
          description: We are having server issues, don't mind us, lol x.
    delete:
      tags:
        - Deposit
      parameters:
        - in: path
          name: deposit_id
          required: true
          description: Deposit ID
          schema:
            type: integer
            format: int32
      summary: Delete a particular deposit.
      description: Get a particular deposit into a user's account and delete it.
      responses:
        "200":
          description: OK!
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Deleted successfully.
        "400":
          description: You are not authorized to do that.
        "404":
          description: Not Found.
        "500":
          description: We are having server issues, don't mind us, lol x.
  "/api/home":
    get:
      tags:
        - Default
      summary: Home route
      description: Returns JSON if site is up and running
      responses:
        "200":
          description: OK!
          content:
            application/json:
              schema:
                properties:
                  value:
                    type: string
  "/api/login":
    post:
      tags:
        - User
      summary: Register user
      description: A route to register user
      requestBody:
        description: Input your credentials to be registered.
        content:
          application/json:
            schema:
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: testing@demo.com
                password:
                  type: string
                  format: password
                  example: thatisme
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  access token:
                    type: string
                  email:
                    type: string
                    format: email
                    example: test@demo.com
                  msg:
                    type: string
                    default: successful
                  refresh token:
                    type: string
        "400":
          description: Email or password is incorrect, please try again!
        "404":
          description: Not Found.
        "500":
          description: We are having server issues, don't mind us, lol x.
  "/api/register":
    post:
      tags:
        - User
      summary: Register user
      description: A route to register user
      requestBody:
        description: Input your credentials to be registered.
        content:
          application/json:
            schema:
              required:
                - email
                - password
                - first name
                - last name
                - accountType
                - role
              properties:
                email:
                  type: string
                  format: email
                  example: testing@demo.com
                password:
                  type: string
                  format: password
                  example: thatisme
                first name:
                  type: string
                  example: Confidence
                last name:
                  type: string
                  example: James
                accountType:
                  type: string
                  example: Savings
                role:
                  type: string
                  example: Customer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
        "400":
          description: The email or phone number is already in our database, try again!
        "404":
          description: Not Found.
        "500":
          description: We are having server issues, don't mind us, lol x.
  "/api/transfers":
    get:
      tags:
        - Transfer
      summary: Get all transfers
      description: A route to list all transfer
      responses:
        "200":
          description: OK!
          content:
            application/json:
              schema:
                properties:
                  role:
                    type: string
                    example: Customer
        "400":
          description: You are not authorized to do that!
        "404":
          description: Not Found.
        "500":
          description: We are having server issues, don't mind us, lol x.
    post:
      tags:
        - Admin
        - Transfer
      summary: Make a deposit
      description: Make a deposit
      requestBody:
        description: Input the sender, receiver and amount to be deposited
        content:
          application/json:
            schema:
              required:
                - account number
                - sender
                - amount
              properties:
                account number:
                  type: string
                  example: 100000000
                sender:
                  type: string
                  example: James Confidence
                amount:
                  type: number
                  format: float
                  example: 50000
      responses:
        "200":
          description: OK!
          content:
            application/json:
              schema:
                properties:
                  msg:
                    type: string
                    example:
                      50000 deposited successfully to Confidence James with
                      account number of 100000000
        "400":
          description: You are not authorized to do this!
        "404":
          description: Not Found.
        "500":
          description: We are having server issues, don't mind us, lol x.
  "/api/users":
    get:
      tags:
        - User
      summary: Get all users
      description: Returns JSON if site is up and running
      responses:
        "200":
          description: OK!
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    email:
                      type: string
                      example: test@demo.com
                    First Name:
                      type: string
                      example: Example
                    Last Name:
                      type: string
                      example: Example
                    Phone Number:
                      type: string
                      example: 23481xxxxxxxx
                    Account Number:
                      type: string
                      format: number
                      example: 1000000000
                    Account Balance:
                      type: number
                      format: float
                      example: 1
                    Account Type:
                      type: string
                      example: Savings
                    Account Status:
                      type: string
                      example: Active
                    Date Of Birth:
                      type: string
                      format: date
                      example: 06-12-1970
                    Date Created:
                      type: string
                      format: date
                      example: 06-12-1970
                    Safe To Spend:
                      type: number
                      format: float
                      example: 5000
                    Date Spend:
                      type: string
                      format: date
                      example: 06-12-1970
                    Role:
                      type: string
                      example: Customer
        "400":
          description: Email or password is incorrect, please try again!
        "404":
          description: Not Found.
        "500":
          description: We are having server issues, don't mind us, lol x.
  "/api/users/{user_id}":
    get:
      tags:
        - User
      summary: Get a specific user
      description: Returns JSON if site is up and running
      parameters:
        - in: path
          name: user_id
          required: true
          description: User ID
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK!
          content:
            application/json:
              schema:
                properties:
                  email:
                    type: string
                    example: test@demo.com
                  First Name:
                    type: string
                    example: Example
                  Last Name:
                    type: string
                    example: Example
                  Phone Number:
                    type: string
                    example: 23481xxxxxxxx
                  Account Number:
                    type: string
                    format: number
                    example: 1000000000
                  Account Balance:
                    type: number
                    format: float
                    example: 1
                  Account Type:
                    type: string
                    example: Savings
                  Account Status:
                    type: string
                    example: Active
                  Date Of Birth:
                    type: string
                    format: date
                    example: 06-12-1970
                  Date Created:
                    type: string
                    format: date
                    example: 06-12-1970
                  Safe To Spend:
                    type: number
                    format: float
                    example: 5000
                  Date Spend:
                    type: string
                    format: date
                    example: 06-12-1970
                  Role:
                    type: string
                    example: Customer
        "400":
          description: Email or password is incorrect, please try again!
        "404":
          description: Not Found.
        "500":
          description: We are having server issues, don't mind us, lol x.
    patch:
      tags:
        - User
      parameters:
        - in: path
          name: user_id
          required: true
          description: User ID
          schema:
            type: integer
            format: int32
      summary: Update User
      description: A route to update a user
      requestBody:
        description: Input your credentials to be update your profile
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  format: email
                  example: testing@demo.com
                first name:
                  type: string
                  example: Confidence
                last name:
                  type: string
                  example: James
                phone number:
                  type: string
                  example: 23481xxxxxxxx
      responses:
        "200":
          description: OK!
          content:
            application/json:
              schema:
                properties:
                  email:
                    type: string
                    example: test@demo.com
                  First Name:
                    type: string
                    example: Example
                  Last Name:
                    type: string
                    example: Example
                  Phone Number:
                    type: string
                    example: 23481xxxxxxxx
                  Account Number:
                    type: string
                    format: number
                    example: 1000000000
                  Account Balance:
                    type: number
                    format: float
                    example: 1
                  Account Type:
                    type: string
                    example: Savings
                  Account Status:
                    type: string
                    example: Active
                  Date Of Birth:
                    type: string
                    format: date
                    example: 06-12-1970
                  Date Created:
                    type: string
                    format: date
                    example: 06-12-1970
                  Safe To Spend:
                    type: number
                    format: float
                    example: 5000
                  Date Spend:
                    type: string
                    format: date
                    example: 06-12-1970
                  Role:
                    type: string
                    example: Customer
        "400":
          description: The email or phone number is already in our database, try again!
        "404":
          description: Not Found.
        "500":
          description: We are having server issues, don't mind us, lol x.
    delete:
      tags:
        - User
      parameters:
        - in: path
          name: user_id
          required: true
          description: User ID
          schema:
            type: integer
            format: int32
      summary: Delete User
      description: A route to delete a user
      responses:
        "200":
          description: OK!
          content:
            application/json:
              schema:
                properties:
                  msg:
                    type: string
                    example: User successfully deleted.
        "400":
          description: The email or phone number is already in our database, try again!
        "404":
          description: Not Found.
        "500":
          description: We are having server issues, don't mind us, lol x.
